version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: "test"
